services:
  postgres:
    image: postgres:16
    container_name: bd2_multimodal_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: bd2_multimodal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bd2_multimodal"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: